<a href="https://colab.research.google.com/github/rootyJeon/deep_stat_study/blob/main/W4_DataLoader_Presentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PBL Dataset

In [ ]:
## timer 메서드 가져오기
import time
def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        computation_time = end_time - start_time
        print(f"Execution time of {func.__name__}: {computation_time} seconds")
        return result
    return wrapper

In [ ]:
## 구글 드라이브 임포트
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
## 압축파일 풀기 -> 구글 드라이브 환경에서 25분 소요
#%cd /content/drive/MyDrive/Colab Notebooks/data
#!unzip "3주차-PBL-data.zip"

In [ ]:
import pickle

## train 피클 확인, 이미지 데이터는 경로 정보만 담겨 있음
with open('/content/drive/MyDrive/Colab Notebooks/data/train.pkl', 'rb') as f:
	train_data = pickle.load(f)
train_data

n  potential                                 position  \
0      5      0.226                 [81, 117, 150, 182, 218]   
1      7      0.448       [93, 114, 132, 150, 167, 185, 206]   
2      5      0.341                 [97, 125, 150, 174, 202]   
3      8      0.390  [82, 104, 123, 141, 158, 176, 195, 217]   
4      8      0.404  [83, 105, 124, 141, 158, 175, 194, 216]   
...   ..        ...                                      ...   
59995  6      0.369            [92, 117, 139, 160, 182, 207]   
59996  8      0.320   [72, 98, 119, 140, 159, 180, 201, 227]   
59997  8      0.266   [62, 91, 115, 138, 161, 184, 208, 237]   
59998  8      0.337   [75, 99, 120, 140, 159, 179, 200, 224]   
59999  6      0.179             [57, 97, 132, 167, 202, 242]   

                    img_path  
0          train/image_0.png  
1          train/image_1.png  
2          train/image_2.png  
3          train/image_3.png  
4          train/image_4.png  
...                      ...  
59995  train/image_59995.png  
59996  train/image_59996.png  
59997  train/image_59997.png  
59998  train/image_59998.png  
59999  train/image_59999.png  

[60000 rows x 4 columns]

In [ ]:
## valid 피클 확인, train과 같이 이미지 데이터는 경로 정보만 담겨 있음
with open('/content/drive/MyDrive/Colab Notebooks/data/valid.pkl', 'rb') as f:
	valid_data = pickle.load(f)
valid_data

n  potential                                 position  \
0     6      0.457           [100, 122, 140, 159, 177, 199]   
1     7      0.291       [74, 102, 127, 150, 172, 197, 225]   
2     6      0.434            [98, 121, 140, 159, 178, 201]   
3     8      0.435  [86, 107, 125, 141, 158, 174, 192, 213]   
4     8      0.401  [83, 105, 124, 141, 158, 175, 194, 216]   
...  ..        ...                                      ...   
9995  6      0.301            [84, 113, 137, 162, 186, 215]   
9996  8      0.345  [76, 100, 121, 140, 159, 178, 199, 223]   
9997  5      0.372                [100, 126, 150, 173, 199]   
9998  6      0.304            [84, 113, 138, 161, 186, 215]   
9999  5      0.445                [106, 129, 150, 170, 193]   

                  img_path  
0        valid/image_0.png  
1        valid/image_1.png  
2        valid/image_2.png  
3        valid/image_3.png  
4        valid/image_4.png  
...                    ...  
9995  valid/image_9995.png  
9996  valid/image_9996.png  
9997  valid/image_9997.png  
9998  valid/image_9998.png  
9999  valid/image_9999.png  

[10000 rows x 4 columns]

In [ ]:
## 토치 라이브러리 임포트 (꼭 이 위치일 필요는 X)
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
device = 'cuda' if torch.cuda.is_available() else 'cpu'

data_dir = ''

In [ ]:
## train_data에서 label만 추출
train_data[['n','potential']]

n  potential
0      5      0.226
1      7      0.448
2      5      0.341
3      8      0.390
4      8      0.404
...   ..        ...
59995  6      0.369
59996  8      0.320
59997  8      0.266
59998  8      0.337
59999  6      0.179

[60000 rows x 2 columns]

In [ ]:
## label의 기초통계량 파악
train_data[['n','potential']].describe()

n     potential
count  60000.000000  60000.000000
mean       6.878217      0.332672
std        1.139638      0.109168
min        5.000000      0.146000
25%        6.000000      0.240000
50%        7.000000      0.332000
75%        8.000000      0.426000
max        8.000000      0.522000

In [ ]:
!pip install Pillow

In [ ]:
from PIL import Image
import numpy as np

## 이미지 파일 경로 설정, train_data의 이미지 경로와 합쳐서 확인
image_path = '/content/drive/MyDrive/Colab Notebooks/data/pbl_data/' + train_data['img_path'][1]

## 그러나 train에는 6만장, valid에는 1만장의 이미지가 있어서 조회 시 부하 발생 ([Errno 5] Input/output error:)
image = Image.open(image_path)

# 이미지를 NumPy 배열로 변환, 출력
image_array = np.array(image)
image_array

OSError: ignored

In [ ]:
## try-except 문으로 변환해서 정상 작동할 때까지 시도
trials = 1
while True:
  try:
    image = Image.open(image_path)
    image_array = np.array(image)
    print("trial ", trials ,": Success \n", image_array)
    break
  except:
    print("trial ", trials, ": Fail")
    trials = trials + 1

trial  1 : Fail
trial  2 : Fail
trial  3 : Success 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
image

In [ ]:
## 레이블의 첫번째 행 확인, 각 레이블은 원소가 2개인 벡터 형태
np.array(train_data[['n','potential']])[0]

array([5.   , 0.226])

In [ ]:
class cumstom_PBL_train_dataset(torch.utils.data.Dataset):
  def __init__(self, train=True, transform=None):

    ## 학습 모드: train이 True이면 train 데이터셋
    if train:
      self.data = train_data
    ## 검증 모드: train이 False이면 valid 데이터셋
    else:
      self.data = valid_data

    ## 레이블은 정보량이 많지 않으므로 target에 전체 레이블 저장
    self.target = np.array(self.data[['n','potential']])

    ## 특별한 변환이 없으면 그대로 tensor로 변환하도록 설정: Tensor class
    if transform is None:
      self.transform = torch.Tensor
    else:
      self.transform = transform

  def __len__(self):
    return len(self.target)

  def __getitem__(self, index):

    ## 위 셀에서 실험한 대로 self.data에 저장한 데이터프레임에서 index에 해당하는 이미지 경로 설정, 불러와서 array 형태로 저장
    image_path = '/content/drive/MyDrive/Colab Notebooks/data/pbl_data/' + self.data['img_path'][index]
    self.input = np.array(Image.open(image_path))

    ## transform에 지정한 변환을 거침: 아무것도 안 하는 경우 Tensor()를 통해 tensor로 변환
    img = self.transform(self.input)
    label = self.transform(self.target[index])

    return img, label

In [ ]:
## Dataset을 지정하고
custom_train_data = cumstom_PBL_train_dataset(train=True)
custom_test_data = cumstom_PBL_train_dataset(train=False)

min_batch = 100

## train_loader와 test_loader에 데이터 적용
train_loader = torch.utils.data.DataLoader(dataset=custom_train_data, batch_size=min_batch, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=custom_test_data, batch_size=min_batch, shuffle=False)

In [ ]:
# x, y 각각 min_batch * 기본 형태 크기의 텐서로 정상 출력됨을 확인
x, y = next(iter(test_loader))
print(x.shape, y.shape)

torch.Size([100, 10, 300]) torch.Size([100, 2])


In [ ]:
x[0]

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [ ]:
y[0]

tensor([6.0000, 0.4570])

## 모델 학습 시도 1
- 정식 모델 학습 X, 회귀 문제를 생략하고 분류 문제만 실험적으로 적용

In [ ]:
class cumstom_PBL_train_dataset2(torch.utils.data.Dataset):
  def __init__(self, train=True, transform=None):

    if train:
      self.data = train_data
    else:
      self.data = valid_data

    ## 포텐셜에 대한 회귀 생략, 양자 개수만 레이블에 일단 입력
    self.target = np.array(self.data[['n']])

    if transform is None:
      self.transform = torch.Tensor
    else:
      self.transform = transform

  def __len__(self):
    return len(self.target)

  def __getitem__(self, index):

    image_path = '/content/drive/MyDrive/Colab Notebooks/data/pbl_data/' + self.data['img_path'][index]
    self.input = np.array(Image.open(image_path))

    img = self.transform(self.input)
    label = self.transform(self.target[index])

    return img, label

In [ ]:
## Dataset 재적용
custom_train_data = cumstom_PBL_train_dataset2(train=True)
custom_test_data = cumstom_PBL_train_dataset2(train=False)

min_batch = 100

train_loader = torch.utils.data.DataLoader(dataset=custom_train_data, batch_size=min_batch, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=custom_test_data, batch_size=min_batch, shuffle=False)

In [ ]:
import pandas as pd

## train과 valid가 서로 다른 레이블을 가지고 있음을 기초통계량으로 먼저 확인
x, y = next(iter(train_loader))
pd.DataFrame(y).describe()

0
count  100.000000
mean     6.950000
std      1.175293
min      5.000000
25%      6.000000
50%      7.000000
75%      8.000000
max      8.000000

In [ ]:
x, y = next(iter(test_loader))
pd.DataFrame(y).describe()

0
count  100.00000
mean     6.73000
std      1.20483
min      5.00000
25%      6.00000
50%      7.00000
75%      8.00000
max      8.00000

In [ ]:
## 3주차 예제에서 다룬 분류 모델 구조를 그대로 적용
class DeepClassification(nn.Module):
    def __init__(self, hidden_variables=[128, 64, 10], input_output_dim=(28*28, 10)):
        super().__init__()
        # Concise Implementation
        self.input_variable_dim = input_output_dim[0]
        self.output_variable_dim = input_output_dim[1]
        self.list_hidden_variable = hidden_variables
        self.layer = nn.Sequential()

        variable_dim = self.input_variable_dim
        for i, hidden_variable in enumerate(self.list_hidden_variable):
            self.layer.add_module('layer_' + str(i), nn.Linear(variable_dim, hidden_variable))
            self.layer.add_module('custom_activation_' + str(i), nn.ReLU())
            variable_dim = hidden_variable
        self.layer.add_module('final_layer', nn.Linear(variable_dim, self.output_variable_dim))

    def forward(self, x):
    # Computes the outputs / predictions
        x = x.view(-1, self.input_variable_dim)
        y_hat = self.layer(x)
        return y_hat

In [33]:
## 레이블의 형태: 각각 원소가 1개인 벡터 형태
## 이 형태로는 loss 계산 시 오류 발생
y

tensor([[6.],
        [7.],
        [6.],
        [8.],
        [8.],
        [5.],
        [8.],
        [7.],
        [7.],
        [8.],
        [6.],
        [5.],
        [6.],
        [6.],
        [7.],
        [8.],
        [8.],
        [5.],
        [8.],
        [7.],
        [8.],
        [8.],
        [7.],
        [5.],
        [8.],
        [7.],
        [5.],
        [5.],
        [8.],
        [7.],
        [8.],
        [5.],
        [6.],
        [8.],
        [5.],
        [6.],
        [5.],
        [8.],
        [8.],
        [8.],
        [5.],
        [8.],
        [8.],
        [5.],
        [8.],
        [6.],
        [6.],
        [7.],
        [6.],
        [8.],
        [6.],
        [5.],
        [7.],
        [5.],
        [8.],
        [8.],
        [6.],
        [5.],
        [6.],
        [5.],
        [6.],
        [8.],
        [8.],
        [8.],
        [6.],
        [8.],
        [5.],
        [6.],
        [6.],
        [5.],
        [8.],
      

In [ ]:
## 우회: 어차피 각각 원소가 1개씩이므로 max 함수를 써서 각각의 원소를 원소 1개짜리 벡터 -> 스칼라로 변환
torch.max(y, axis=1)[0].to(torch.long)

tensor([6, 7, 6, 8, 8, 5, 8, 7, 7, 8, 6, 5, 6, 6, 7, 8, 8, 5, 8, 7, 8, 8, 7, 5,
        8, 7, 5, 5, 8, 7, 8, 5, 6, 8, 5, 6, 5, 8, 8, 8, 5, 8, 8, 5, 8, 6, 6, 7,
        6, 8, 6, 5, 7, 5, 8, 8, 6, 5, 6, 5, 6, 8, 8, 8, 6, 8, 5, 6, 6, 5, 8, 6,
        6, 7, 7, 8, 5, 5, 8, 8, 7, 8, 8, 8, 8, 5, 8, 8, 6, 8, 6, 5, 6, 7, 6, 8,
        5, 8, 8, 7])

In [ ]:
## tr의
def make_train_step(model, loss_fn, optimizer):
    def train_step_fn(x, y):

        model.train()
        y_hat = model(x)
        print(torch.sum(torch.argmax(y_hat, axis=1) == torch.max(y, axis=1)[0].to(torch.long)))
        loss = loss_fn(y_hat, torch.max(y, axis=1)[0].to(torch.long))

        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        return loss.item()
    return train_step_fn

In [ ]:
@timer
def train_model_classification(epochs=1000, eval_test_accuracy=False):

    def evaluate_step(x, y):
      y_hat = model(x)
      print(y_hat)
      print(torch.argmax(y_hat, axis=1))
      print(torch.max(y, axis=1)[0].to(torch.long))
      result = torch.sum(torch.argmax(y_hat, axis=1) == torch.max(y, axis=1)[0].to(torch.long))
      print(result,"\n")
      return result, len(y)

    train_losses = []
    for epoch in range(epochs):
        mini_batch_losses = []
        step_time = []
        step_time.append(time.time())
        for x_minibatch, y_minibatch in train_loader:
            x_minibatch = x_minibatch.to(device)
            y_minibatch = y_minibatch.to(device)
            mini_batch_loss = train_step(x_minibatch, y_minibatch)
            mini_batch_losses.append(mini_batch_loss)
            step_time.append(time.time())
            print("step time: ", round(step_time[-1] - step_time[-2], 4) , ", loss:", round(mini_batch_loss, 4), ", epoch ",epoch, ", minibatch", len(mini_batch_losses), "\n")

        if (epoch + 1) % 1 == 0:
            loss = np.mean(mini_batch_losses)
            print("train loss at {} epoch:{}".format(epoch + 1, loss))
            train_losses.append(loss)

            if eval_test_accuracy:
                with torch.no_grad():
                    test_accuracy = 0
                    test_result = 0
                    test_cnt = 0
                    for x_minibatch_test, y_minibatch_test in test_loader:
                        x_minibatch_test = x_minibatch_test.to(device)
                        y_minibatch_test = y_minibatch_test.to(device)
                        result, cnt = evaluate_step(x_minibatch_test, y_minibatch_test)
                        test_result += result
                        test_cnt += cnt
                    test_accuracy = 100 * test_result / test_cnt
                    print("test accuracy at {} epoch: {}%".format(epoch + 1, test_accuracy))

            checkpoint = {'epochs': epochs,
                          'model_state_dict': model.state_dict(),
                          'optimizer_state_dict': optimizer.state_dict(),
                          'train_loss': train_losses,
                          'test_accuracy': test_accuracy
                          }
            torch.save(checkpoint, 'model_checkpoint.pth')


    return train_losses, test_accuracy

In [ ]:
model = DeepClassification(input_output_dim=(10*300, 9)).to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)
train_step = make_train_step(model, loss_fn, optimizer)

In [ ]:
## batch를 600번 학습해야 한 epoch가 끝나는데, 한번 학습에 25초 내외가 소요됨 - 정상적인 학습 불가능
## 모델 학습이나 loss 계산에는 시간이 오래 걸리지 않으나, 이미지 load에서 시간이 크게 소요됨
## 마운트된 구글 드라이브 폴더 내에 과도하게 많은 파일이 있어 조회 작업에서 부하가 발생한 것으로 추정 - 따라서 부적절한 방식
train_loss, test_accuracy = train_model_classification(epochs=5, eval_test_accuracy=True)

tensor(9)
step time:  25.7097 , loss: 2.8759 , epoch  0 , minibatch 1 

tensor(37)
step time:  26.8276 , loss: 1.708 , epoch  0 , minibatch 2 

tensor(43)
step time:  24.4845 , loss: 2.0375 , epoch  0 , minibatch 3 

tensor(14)
step time:  26.4578 , loss: 2.5476 , epoch  0 , minibatch 4 

tensor(45)
step time:  26.2534 , loss: 1.6137 , epoch  0 , minibatch 5 

tensor(58)
step time:  25.2178 , loss: 1.2789 , epoch  0 , minibatch 6 

tensor(61)
step time:  25.8813 , loss: 1.1008 , epoch  0 , minibatch 7 

tensor(63)
step time:  25.2282 , loss: 1.0315 , epoch  0 , minibatch 8 

tensor(57)
step time:  24.8803 , loss: 1.0516 , epoch  0 , minibatch 9 

tensor(65)
step time:  25.6362 , loss: 0.9585 , epoch  0 , minibatch 10 

tensor(66)
step time:  24.7419 , loss: 0.8461 , epoch  0 , minibatch 11 

tensor(71)
step time:  25.2821 , loss: 0.7398 , epoch  0 , minibatch 12 

tensor(74)
step time:  25.56 , loss: 0.6841 , epoch  0 , minibatch 13 

tensor(57)
step time:  24.7659 , loss: 0.9955 , epo

KeyboardInterrupt: ignored

In [ ]:
## validation accuracy 코드가 정상 작동되는 것을 확인하기 위해 next(iter(test_loader))로 한 batch만 예시로 뽑아 정확도 계산
def evaluate_step(x, y):
  y_hat = model(x)
  print(y_hat)
  print(torch.argmax(y_hat, axis=1))
  print(torch.max(y, axis=1)[0].to(torch.long))
  result = torch.sum(torch.argmax(y_hat, axis=1) == torch.max(y, axis=1)[0].to(torch.long))
  print(result,"\n")
  return result, len(y)

test_accuracy = 0
test_result = 0
test_cnt = 0
epoch = 0

x_minibatch_test, y_minibatch_test = next(iter(test_loader))
x_minibatch_test = x_minibatch_test.to(device)
y_minibatch_test = y_minibatch_test.to(device)
result, cnt = evaluate_step(x_minibatch_test, y_minibatch_test)
test_result += result
test_cnt += cnt
test_accuracy = 100 * test_result / test_cnt
print("test accuracy at {} epoch: {}%".format(epoch + 1, test_accuracy))

tensor([[-4.0943e+00,  1.2567e+00,  1.1568e+00, -4.7863e+00,  2.8473e+00,
          6.3419e-01,  4.8458e+00, -1.1495e+00,  1.3943e+00],
        [-9.6350e+00,  5.9377e+00, -1.1364e+01, -1.1448e+01, -2.3704e+00,
          1.0669e+01,  7.5722e+00,  1.2263e+01,  2.4874e+00],
        [-4.9505e+00,  1.9890e+00, -1.1701e+00, -5.6253e+00,  1.4719e+00,
          2.4076e+00,  5.0087e+00,  1.4728e+00,  1.4964e+00],
        [-3.8273e+00, -4.0312e+00, -5.2411e-01, -5.1593e+00,  2.5295e-01,
         -1.7003e+00,  1.4413e+00, -3.9789e+00,  3.7942e+00],
        [-5.6925e+00, -3.7975e+00, -1.4725e+00, -6.3152e+00, -1.6791e+00,
         -5.8491e-01,  2.3670e+00, -2.1416e+00,  4.4115e+00],
        [-7.4253e+00,  4.8490e+00, -9.3289e+00, -9.2370e+00, -1.2175e+00,
          8.5379e+00,  5.9511e+00,  9.6083e+00,  1.8500e+00],
        [-5.9421e+00, -5.8127e+00, -2.9235e+00, -8.7333e+00, -1.1510e+00,
         -4.0417e-01,  2.4653e+00, -3.3113e+00,  6.7290e+00],
        [-1.1616e+01,  4.5922e+00, -1.2847e+01, 